% DEMO2_CYLINDER1DM Augmented LQG and feedback adaptation experiment.
%
% T1 compares fixed LQG with its Youla-Q RLS augmentation. T2 uses the
% selected normalized-LMS update and retains Q-RLS as a failure comparison.

clear; close all; clc;
scriptDir = fileparts(mfilename('fullpath'));
run(fullfile(scriptDir, 'startup.m'));

%% Part 0 - Experiment setup
signals = load_cylinder1dm_signals('evaluation');

fprintf('========== Demo2: augmented LQG + feedback adaptation ==========\n');
fprintf('  Evaluation split: seed %d, T1/T2 held out\n', signals.rng_seed);
fprintf('  Information: residual output feedback only\n');
fprintf('  Actuator: hard limit 5, tuning demand limit 4\n\n');

%% Part 1 - T1 fixed: LQG for a known tone
paramsT1f = struct( ...
    'Q_lqr', 1, 'R_lqr', 1e-4, ...
    'Qn_plant', 1e-4, 'Qn_dist', 0.1, 'Rn', 0.1, ...
    'control_scale', 1, 'ramp_seconds', 0.1);
resultT1f = controller_demo2(signals, 'T1', 'fixed', paramsT1f);

%% Part 2 - T1 adaptive: same LQG base + Youla-Q RLS
paramsT1a = struct( ...
    'Q_lqr', 1, 'R_lqr', 1e-4, ...
    'Qn_plant', 1e-4, 'Qn_dist', 0.1, 'Rn', 0.1, ...
    'control_scale', 1, 'ramp_seconds', 0.1, ...
    'nQ', 4, 'lambda', 0.995, 'F_init', 0.1, ...
    'adaptation_gain', 0.1, 'adaptation_method', 'rls', ...
    'theta_norm_limit', 8);
resultT1a = controller_demo2(signals, 'T1', 'adaptive', paramsT1a);

%% Part 3 - T2 adaptive: normalized-LMS on a reverse chirp
paramsT2 = struct( ...
    'Q_lqr', 1, 'R_lqr', 1e-2, ...
    'Qn_plant', 1e-4, 'Qn_dist', 0.1, 'Rn', 0.1, ...
    'control_scale', 1, 'ramp_seconds', 0.1, ...
    'bp_band', [280 440], 'adaptive_warmup_seconds', 0.5, ...
    'theta_norm_limit', 8, 'nQ', 32, ...
    'adaptation_gain', 0.1, 'adaptation_method', 'lms', ...
    'lms_epsilon', 1e-6, 'lms_leakage', 0);
resultT2 = controller_demo2(signals, 'T2', 'adaptive', paramsT2);

%% Part 4 - T2 Q-RLS failure comparison
paramsRls = paramsT2;
paramsRls.adaptation_method = 'rls';
paramsRls.adaptation_gain = 0.15;
paramsRls.lambda = 0.98;
paramsRls.F_init = 0.1;
resultRls = controller_demo2(signals, 'T2', 'adaptive', paramsRls);

%% Part 5 - Frozen evaluation overview
figureDir = fullfile(scriptDir, 'figures', 'cylinder1dm_2k', 'demo2');
overview = struct('T1_fixed', resultT1f, ...
    'T1_adaptive', resultT1a, 'T2', resultT2);
plot_demo_overview(overview, fullfile(figureDir, 'demo2_analysis.png'));

%% Part 6 - Summary
fprintf('\n========== Demo2 summary ==========\n');
fprintf('  T1 fixed LQG:       %6.2f dB  demand %.3f  clips %d\n', ...
    resultT1f.supp_db, resultT1f.extra.u_demand_max, ...
    resultT1f.extra.saturation_count);
fprintf('  T1 adaptive Q-RLS:  %6.2f dB  demand %.3f  clips %d  t_conv %.2f s\n', ...
    resultT1a.supp_db, resultT1a.extra.u_demand_max, ...
    resultT1a.extra.saturation_count, resultT1a.t_conv_s);
fprintf('  T2 LMS selected:    %6.2f dB  demand %.3f  clips %d  t_conv %.2f s\n', ...
    resultT2.supp_db, resultT2.extra.u_demand_max, ...
    resultT2.extra.saturation_count, resultT2.t_conv_s);
fprintf('  T2 Q-RLS compare:   %6.2f dB  demand %.3f  clips %d  t_conv %.2f s\n', ...
    resultRls.supp_db, resultRls.extra.u_demand_max, ...
    resultRls.extra.saturation_count, resultRls.t_conv_s);
