function stage = run_cylinder1dm_stage(scope)
%RUN_CYLINDER1DM_STAGE Tune, freeze, and evaluate Demo1-5.
%
%   默认只运行 T1/T2 主实验。宽带 T3 使用
%   run_cylinder1dm_stage('broadband') 独立运行，避免其失败边界
%   干扰 fixed/adaptive 主比较的观察。
%
%   阶段流程全部在本文件内：候选调参 (tune_demo1234_controllers)、
%   冻结评价、Demo2 T2 的 RLS/LMS 对照 (compare_demo2_t2_adaptation)
%   都是局部函数，controller_demo1/2/3/4 与报告生成在 internal/。

if nargin < 1, scope = 'main'; end
scope = validatestring(scope, {'main', 'broadband'});

testDir = fileparts(mfilename('fullpath'));
run(fullfile(testDir, 'startup.m'));

% The loader validates the cached suite's path-family metadata and rebuilds
% it when the default model family changes (e.g. ARMAX -> measured FIR).
suite = load_cylinder1dm_signals('suite');

if strcmp(scope, 'main')
    outputDir = fullfile(testDir, 'output', 'cylinder1dm_2k', 'demo1234_stage');
    artifactPrefix = 'demo1234';
else
    outputDir = fullfile(testDir, 'output', 'cylinder1dm_2k', 'broadband_stage');
    artifactPrefix = 'broadband';
end
figureDir = fullfile(testDir, 'figures', 'cylinder1dm_2k');
if ~isfolder(outputDir), mkdir(outputDir); end
if ~isfolder(figureDir), mkdir(figureDir); end

[selections, tuningTable] = tune_demo1234_controllers(suite.calibration, scope);
evaluationResults = cell(numel(selections), 1);
summaryRows = cell(numel(selections), 14);

fprintf('\n========== Frozen held-out evaluation ==========' );
fprintf('\n');
for index = 1:numel(selections)
    selection = selections(index);
    runner = runner_for_demo(selection.demo);
    result = runner(suite.evaluation, selection.test, ...
        selection.variant, selection.params);
    evaluationResults{index} = result;

    [stable, stabilityValue] = stability_status(result);
    success = stable ...
        && result.supp_db >= 20 ...
        && result.extra.u_demand_max <= suite.meta.tuning_peak_limit ...
        && result.extra.saturation_count == 0;
    if strcmp(selection.demo, 'demo5')
        success = success && result.extra.case_a_applicable;
    end

    summaryRows(index, :) = {selection.demo, selection.variant, ...
        selection.test, selection.candidate, selection.feasible, success, ...
        selection.calibration_result.supp_db, result.supp_db, ...
        result.extra.u_demand_max, result.extra.saturation_count, stable, ...
        stabilityValue, result.u_rms, jsonencode(selection.params)};

    fprintf('  %-5s %-8s %s: %7.2f dB raw=%6.3f sat=%d success=%d\n', ...
        selection.demo, selection.variant, selection.test, result.supp_db, ...
        result.extra.u_demand_max, result.extra.saturation_count, success);
end

summary = cell2table(summaryRows, 'VariableNames', { ...
    'demo', 'variant', 'test', 'candidate', 'calibration_feasible', ...
    'evaluation_success', 'calibration_suppression_db', ...
    'evaluation_suppression_db', 'control_demand_max', ...
    'saturation_count', 'stable', 'stability_value', 'control_rms', ...
    'params_json'});

stage = struct();
stage.scope = scope;
stage.suite = suite;
stage.selections = selections;
stage.tuning = tuningTable;
stage.evaluation_results = evaluationResults;
stage.summary = summary;
stage.generated_at = datetime('now');

if strcmp(scope, 'main')
    demo2T2Index = find(strcmp({selections.demo}, 'demo2') ...
        & strcmp({selections.test}, 'T2'), 1);
    stage.demo2_t2_comparison = compare_demo2_t2_adaptation( ...
        suite.calibration, suite.evaluation, selections(demo2T2Index), ...
        evaluationResults{demo2T2Index});
end

stageFile = fullfile(outputDir, sprintf('%s_stage_results.mat', artifactPrefix));
save(stageFile, 'stage');
writetable(tuningTable, fullfile(outputDir, sprintf('%s_tuning.csv', artifactPrefix)));
writetable(summary, fullfile(outputDir, sprintf('%s_evaluation.csv', artifactPrefix)));

if strcmp(scope, 'main')
    writetable(stage.demo2_t2_comparison.tuning, ...
        fullfile(outputDir, 'demo2_t2_adaptation.csv'));
    generate_demo1234_reports(stage, figureDir, testDir, 'demo2', 't2');
    generate_demo1234_reports(stage, figureDir, testDir, '', 'report');
    if usejava('desktop')
        render_cylinder1dm();
    else
        fprintf(['Headless mode: main figures were not rendered automatically. ' ...
            'Run render_cylinder1dm() in desktop MATLAB.\n']);
    end
    reportFile = fullfile(testDir, 'DEMO1234_STAGE_REPORT.md');
else
    generate_broadband_report(stage, figureDir, testDir, 'report');
    if usejava('desktop')
        render_cylinder1dm('broadband');
    else
        fprintf(['Headless mode: broadband figures were not rendered automatically. ' ...
            'Run render_cylinder1dm(''broadband'') in desktop MATLAB.\n']);
    end
    reportFile = fullfile(testDir, 'BROADBAND_CYLINDER1DM_REPORT.md');
end

fprintf('\nStage MAT: %s\n', stageFile);
fprintf('Stage report: %s\n', reportFile);
end

function runner = runner_for_demo(demo)
switch demo
    case 'demo1'
        runner = @controller_demo1;
    case 'demo2'
        runner = @controller_demo2;
    case 'demo3'
        runner = @controller_demo3;
    case 'demo4'
        runner = @controller_demo4;
    case 'demo5'
        runner = @controller_demo5;
    case 'demo5_imc'
        runner = @controller_imc_fxlms;
    otherwise
        error('run_cylinder1dm_stage:UnknownDemo', 'Unknown demo: %s', demo);
end
end

function [stable, value] = stability_status(result)
stable = true;
value = NaN;
switch result.demo
    case 'demo1'
        if isfield(result.extra.design, 'closed_loop_radius')
            value = max(result.extra.design.closed_loop_radius, ...
                result.extra.design.controller_radius);
            stable = value < 1;
        end
    case 'demo2'
        value = result.extra.max_eig_Acl;
        if isfield(result.extra, 'max_eig_T12')
            value = max(value, result.extra.max_eig_T12);
        end
        stable = value < 1;
    case 'demo3'
        if isfield(result.extra, 'F_den')
            value = max(abs(roots(result.extra.F_den)));
            stable = value < 1;
        end
    case 'demo4'
        value = max(result.extra.design.closed_loop_radius, ...
            result.extra.design.controller_radius);
        stable = value < 1;
    case 'demo5'
        stable = result.extra.numeric_failure_count == 0 ...
            && all(isfinite([result.supp_db, result.extra.u_demand_max])) ...
            && ~result.extra.frequency_bound_hit;
        value = double(stable);
    case 'imc_fxlms'
        stable = result.extra.numeric_failure_count == 0 ...
            && all(isfinite([result.supp_db, result.extra.u_demand_max]));
        value = double(stable);
end
end

%% ========================================================================
% 候选调参：在校准信号上为每个 Demo/场景选出冻结参数
%% ========================================================================

function [selections, tuningTable] = tune_demo1234_controllers(calibrationSignals, scope)
specs = tuning_specs();
isBroadband = strcmp({specs.test}, 'T3');
if strcmp(scope, 'broadband')
    specs = specs(isBroadband);
else
    specs = specs(~isBroadband);
end
rowData = cell(0, 12);
selections = repmat(struct( ...
    'demo', '', 'test', '', 'variant', '', 'candidate', '', ...
    'params', struct(), 'calibration_result', struct(), ...
    'feasible', false), numel(specs), 1);

for specIndex = 1:numel(specs)
    spec = specs(specIndex);
    candidateResults = cell(numel(spec.candidates), 1);
    scores = -inf(numel(spec.candidates), 1);
    feasible = false(numel(spec.candidates), 1);

    fprintf('\n--- Tune %s/%s/%s ---\n', spec.demo, spec.variant, spec.test);
    for candidateIndex = 1:numel(spec.candidates)
        candidate = spec.candidates{candidateIndex};
        errorMessage = '';
        try
            result = spec.runner(calibrationSignals, spec.test, ...
                spec.variant, candidate.params);
            [feasible(candidateIndex), stable] = is_feasible(result);
            scores(candidateIndex) = candidate_score(result, ...
                feasible(candidateIndex), stable);
            candidateResults{candidateIndex} = result;
            rowData(end+1, :) = {spec.demo, spec.variant, spec.test, ...
                candidate.name, false, feasible(candidateIndex), stable, ...
                result.supp_db, result.extra.u_demand_max, ...
                result.extra.saturation_count, jsonencode(candidate.params), ''}; %#ok<AGROW>
        catch exception
            errorMessage = exception.message;
            rowData(end+1, :) = {spec.demo, spec.variant, spec.test, ...
                candidate.name, false, false, false, NaN, NaN, NaN, ...
                jsonencode(candidate.params), errorMessage}; %#ok<AGROW>
        end
        if isempty(errorMessage)
            fprintf('  %-18s supp=%7.2f dB raw=%6.3f sat=%d feasible=%d\n', ...
                candidate.name, result.supp_db, result.extra.u_demand_max, ...
                result.extra.saturation_count, feasible(candidateIndex));
        else
            fprintf('  %-18s ERROR %s\n', candidate.name, errorMessage);
        end
    end

    feasibleIndices = find(feasible);
    if isempty(feasibleIndices)
        [~, selectedIndex] = max(scores);
    else
        [~, localIndex] = max(scores(feasibleIndices));
        selectedIndex = feasibleIndices(localIndex);
    end

    selectedCandidate = spec.candidates{selectedIndex};
    selections(specIndex).demo = spec.demo;
    selections(specIndex).test = spec.test;
    selections(specIndex).variant = spec.variant;
    selections(specIndex).candidate = selectedCandidate.name;
    selections(specIndex).params = selectedCandidate.params;
    selections(specIndex).calibration_result = candidateResults{selectedIndex};
    selections(specIndex).feasible = feasible(selectedIndex);

    rowsForSpec = strcmp(rowData(:, 1), spec.demo) ...
        & strcmp(rowData(:, 2), spec.variant) ...
        & strcmp(rowData(:, 3), spec.test);
    rowIndices = find(rowsForSpec);
    rowData{rowIndices(selectedIndex), 5} = true;
end

tuningTable = cell2table(rowData, 'VariableNames', { ...
    'demo', 'variant', 'test', 'candidate', 'selected', 'feasible', ...
    'stable', 'suppression_db', 'control_demand_max', ...
    'saturation_count', 'params_json', 'error_message'});
end

function specs = tuning_specs()
specs = repmat(struct('demo', '', 'test', '', 'variant', '', ...
    'runner', [], 'candidates', {{}}), 21, 1);

specs(1) = make_spec('demo1', 'T1', 'fixed', @controller_demo1, ...
    named_sweep('f', 'f_design', [350 357 361 365]));
specs(2) = make_spec('demo1', 'T1', 'adaptive', @controller_demo1, { ...
    candidate('q2_l098', struct('nQ', 2, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q2_l0995', struct('nQ', 2, 'lambda1', 0.995, 'F_diag', 1e-3)), ...
    candidate('q2_l0999', struct('nQ', 2, 'lambda1', 0.999, 'F_diag', 1e-3))});
specs(3) = make_spec('demo1', 'T2', 'adaptive', @controller_demo1, { ...
    candidate('q2_l098', struct('nQ', 2, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q4_l098', struct('nQ', 4, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q2_l0995', struct('nQ', 2, 'lambda1', 0.995, 'F_diag', 1e-3)), ...
    candidate('q4_l0995', struct('nQ', 4, 'lambda1', 0.995, 'F_diag', 1e-3))});
specs(4) = make_spec('demo1', 'T3', 'adaptive', @controller_demo1, { ...
    candidate('q2_l098', struct('nQ', 2, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q4_l098', struct('nQ', 4, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q6_l0995', struct('nQ', 6, 'lambda1', 0.995, 'F_diag', 1e-4)), ...
    candidate('q8_l0995', struct('nQ', 8, 'lambda1', 0.995, 'F_diag', 1e-4))});

lqgAggressive = struct('Q_lqr', 1, 'R_lqr', 1e-4, ...
    'Qn_plant', 1e-4, 'Qn_dist', 0.1, 'Rn', 0.1, ...
    'control_scale', 1, 'ramp_seconds', 0.1);
specs(5) = make_spec('demo2', 'T1', 'fixed', @controller_demo2, { ...
    candidate('aggressive', lqgAggressive), ...
    candidate('r_1e3', setfield(lqgAggressive, 'R_lqr', 1e-3)), ... %#ok<SFLD>
    candidate('r_1e2', setfield(lqgAggressive, 'R_lqr', 1e-2)), ... %#ok<SFLD>
    candidate('default', struct())});
specs(6) = make_spec('demo2', 'T1', 'adaptive', @controller_demo2, { ...
    candidate('q4_l098', merge_params(lqgAggressive, ...
        struct('nQ', 4, 'lambda', 0.98, 'F_init', 0.1, 'adaptation_gain', 0.1))), ...
    candidate('q4_l0995', merge_params(lqgAggressive, ...
        struct('nQ', 4, 'lambda', 0.995, 'F_init', 0.1, 'adaptation_gain', 0.1))), ...
    candidate('q4_l0999', merge_params(lqgAggressive, ...
        struct('nQ', 4, 'lambda', 0.999, 'F_init', 0.1, 'adaptation_gain', 0.1)))});
lqgT2Adaptive = struct('Q_lqr', 1, 'R_lqr', 1e-2, ...
    'Qn_plant', 1e-4, 'Qn_dist', 0.1, 'Rn', 0.1, ...
    'control_scale', 1, 'ramp_seconds', 0.1, ...
    'bp_band', [280 440], 'adaptive_warmup_seconds', 0.5, ...
    'theta_norm_limit', 8);
specs(7) = make_spec('demo2', 'T2', 'adaptive', @controller_demo2, { ...
    candidate('lms_n32_mu0.01', merge_params(lqgT2Adaptive, ...
        struct('nQ', 32, 'adaptation_method', 'lms', ...
        'lms_epsilon', 1e-6, 'lms_leakage', 0, 'adaptation_gain', 0.01))), ...
    candidate('lms_n32_mu0.03', merge_params(lqgT2Adaptive, ...
        struct('nQ', 32, 'adaptation_method', 'lms', ...
        'lms_epsilon', 1e-6, 'lms_leakage', 0, 'adaptation_gain', 0.03))), ...
    candidate('lms_n32_mu0.1', merge_params(lqgT2Adaptive, ...
        struct('nQ', 32, 'adaptation_method', 'lms', ...
        'lms_epsilon', 1e-6, 'lms_leakage', 0, 'adaptation_gain', 0.1)))});
specs(8) = make_spec('demo2', 'T3', 'fixed', @controller_demo2, { ...
    candidate('r_1e2', setfield(lqgAggressive, 'R_lqr', 1e-2)), ... %#ok<SFLD>
    candidate('r_1e1', setfield(lqgAggressive, 'R_lqr', 1e-1)), ... %#ok<SFLD>
    candidate('r_1', setfield(lqgAggressive, 'R_lqr', 1)), ... %#ok<SFLD>
    candidate('default', struct())});

specs(9) = make_spec('demo3', 'T1', 'fixed', @controller_demo3, { ...
    candidate('fir8', struct('N_fir', 8, 'f_design', 357)), ...
    candidate('fir16', struct('N_fir', 16, 'f_design', 357)), ...
    candidate('fir24', struct('N_fir', 24, 'f_design', 357))});
specs(10) = make_spec('demo3', 'T1', 'adaptive', @controller_demo3, { ...
    candidate('imc_n32_mu0.003', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.003, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10)), ...
    candidate('imc_n32_mu0.005', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.005, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10)), ...
    candidate('imc_n32_mu0.01', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.01, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10))});
specs(11) = make_spec('demo3', 'T2', 'adaptive', @controller_demo3, { ...
    candidate('imc_n32_mu0.003', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.003, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10)), ...
    candidate('imc_n32_mu0.005', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.005, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10)), ...
    candidate('imc_n32_mu0.01', struct('N_fir', 8, 'N_nlms', 32, 'mu_nlms', 0.01, ...
        'f_design', 357, 'adaptive_structure', 'imc_fxnlms', 'theta_norm_limit', 10))});
specs(12) = make_spec('demo3', 'T3', 'adaptive', @controller_demo3, { ...
    candidate('n64_mu0.01', struct('N_nlms', 64, 'mu_nlms', 0.01)), ...
    candidate('n128_mu0.05', struct('N_nlms', 128, 'mu_nlms', 0.05))});

% Demo4: eMOPSO 离线设计中央 RST (阶数约束: 无陷波 nX<=9，二阶陷波 nX<=11)。
% T1 比较中央设计本身；T2/T3 在冻结中央控制器上运行与 demo1 相同的
% Youla-Q RLS，比较"同一自适应律、不同中央设计"。
specs(13) = make_spec('demo4', 'T1', 'fixed', @controller_demo4, { ...
    candidate('t1_nx4_fn357', struct('nX', 4, 'nY', 2, 'f_notch', 357, ...
        'n_pop', 40, 'k_max', 80)), ...
    candidate('t1_nx6_fn357', struct('nX', 6, 'nY', 3, 'f_notch', 357, ...
        'n_pop', 50, 'k_max', 100)), ...
    candidate('t1_nx10_fn357', struct('nX', 10, 'nY', 5, 'f_notch', 357, ...
        'n_pop', 60, 'k_max', 120))});
specs(14) = make_spec('demo4', 'T1', 'adaptive', @controller_demo4, { ...
    candidate('q4_l098', struct('nX', 10, 'nY', 5, 'f_notch', 357, ...
        'n_pop', 60, 'k_max', 120, 'nQ', 4, 'lambda1', 0.98, 'F_diag', 1e-3)), ...
    candidate('q4_l0995', struct('nX', 10, 'nY', 5, 'f_notch', 357, ...
        'n_pop', 60, 'k_max', 120, 'nQ', 4, 'lambda1', 0.995, 'F_diag', 1e-3)), ...
    candidate('q4_l0999', struct('nX', 10, 'nY', 5, 'f_notch', 357, ...
        'n_pop', 60, 'k_max', 120, 'nQ', 4, 'lambda1', 0.999, 'F_diag', 1e-3))});
demo4T2Centre = struct('nX', 10, 'nY', 5, 'f_notch', 357, ...
    'n_pop', 60, 'k_max', 120);
specs(15) = make_spec('demo4', 'T2', 'adaptive', @controller_demo4, { ...
    candidate('q4_l098', merge_params(demo4T2Centre, ...
        struct('nQ', 4, 'lambda1', 0.98, 'F_diag', 1e-3))), ...
    candidate('q8_l098', merge_params(demo4T2Centre, ...
        struct('nQ', 8, 'lambda1', 0.98, 'F_diag', 1e-3))), ...
    candidate('q4_l0995', merge_params(demo4T2Centre, ...
        struct('nQ', 4, 'lambda1', 0.995, 'F_diag', 1e-3)))});
demo4T3Centre = struct('nX', 6, 'nY', 3, 'f_notch', [], ...
    'n_pop', 50, 'k_max', 100);
specs(16) = make_spec('demo4', 'T3', 'adaptive', @controller_demo4, { ...
    candidate('q4_l098', merge_params(demo4T3Centre, ...
        struct('nQ', 4, 'lambda1', 0.98, 'F_diag', 1e-3))), ...
    candidate('q8_l0995', merge_params(demo4T3Centre, ...
        struct('nQ', 8, 'lambda1', 0.995, 'F_diag', 1e-4)))});

% Demo5: Marino-Tomei Case A and its pure-feedback IMC-FxLMS baseline.
% The formal FIR Marino-Tomei candidates use updated-state output timing,
% matching the reference demo and the causal sampled-data implementation.
% The previous-state variant is retained only by test_demo5_diagnostics as
% a discrete phase-boundary regression probe.
% T2 is retained even though its discrete effective response crosses zero; all such candidates
% are expected to be marked infeasible by the Case A applicability check.
specs(17) = make_spec('demo5', 'T1', 'fixed', @controller_demo5, {
    candidate('f357_k1e-4', struct('q', 1, 'k', 1e-4, 'epsilon', 0, ...
        'freq_init_hz', 357, 'method', 'exact', 'ramp_seconds', 0.5, ...
        'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f357_k3e-4', struct('q', 1, 'k', 3e-4, 'epsilon', 0, ...
        'freq_init_hz', 357, 'method', 'exact', 'ramp_seconds', 0.5, ...
        'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f357_k1e-3', struct('q', 1, 'k', 1e-3, 'epsilon', 0, ...
        'freq_init_hz', 357, 'method', 'exact', 'ramp_seconds', 0.5, ...
        'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f357_k3e-3', struct('q', 1, 'k', 3e-3, 'epsilon', 0, ...
        'freq_init_hz', 357, 'method', 'exact', 'ramp_seconds', 0.5, ...
        'dc_cancel', false, 'output_timing', 'updated'))});
specs(18) = make_spec('demo5', 'T1', 'adaptive', @controller_demo5, {
    candidate('f350_k3e-4_e1e-3', struct('q', 1, 'k', 3e-4, ...
        'epsilon', 1e-3, 'freq_init_hz', 350, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f350_k1e-3_e3e-4', struct('q', 1, 'k', 1e-3, ...
        'epsilon', 3e-4, 'freq_init_hz', 350, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f350_k1e-3_e3e-5', struct('q', 1, 'k', 1e-3, ...
        'epsilon', 3e-5, 'freq_init_hz', 350, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f350_k3e-3_e1e-4', struct('q', 1, 'k', 3e-3, ...
        'epsilon', 1e-4, 'freq_init_hz', 350, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f350_k3e-3_e1e-5', struct('q', 1, 'k', 3e-3, ...
        'epsilon', 1e-5, 'freq_init_hz', 350, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated'))});
specs(19) = make_spec('demo5', 'T2', 'adaptive', @controller_demo5, {
    candidate('f300_k1e-4_e1e-4', struct('q', 1, 'k', 1e-4, ...
        'epsilon', 1e-4, 'freq_init_hz', 300, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f300_k3e-4_e1e-4', struct('q', 1, 'k', 3e-4, ...
        'epsilon', 1e-4, 'freq_init_hz', 300, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated')), ...
    candidate('f420_k3e-4_e1e-4', struct('q', 1, 'k', 3e-4, ...
        'epsilon', 1e-4, 'freq_init_hz', 420, 'method', 'exact', ...
        'ramp_seconds', 0.5, 'dc_cancel', false, 'output_timing', 'updated'))});
specs(20) = make_spec('demo5_imc', 'T1', 'adaptive', @controller_imc_fxlms, {
    candidate('fir64_mu0.01', struct('N_fir', 64, 'mu', 0.01, ...
        'delta', 1e-4, 'ramp_seconds', 0.5, 'norm_limit', 10)), ...
    candidate('fir64_mu0.02', struct('N_fir', 64, 'mu', 0.02, ...
        'delta', 1e-4, 'ramp_seconds', 0.5, 'norm_limit', 10))});
specs(21) = make_spec('demo5_imc', 'T2', 'adaptive', @controller_imc_fxlms, {
    candidate('fir64_mu0.01', struct('N_fir', 64, 'mu', 0.01, ...
        'delta', 1e-4, 'ramp_seconds', 0.5, 'norm_limit', 10)), ...
    candidate('fir64_mu0.02', struct('N_fir', 64, 'mu', 0.02, ...
        'delta', 1e-4, 'ramp_seconds', 0.5, 'norm_limit', 10))});
end

function spec = make_spec(demo, test, variant, runner, candidates)
spec = struct('demo', demo, 'test', test, 'variant', variant, ...
    'runner', runner, 'candidates', {candidates});
end

function candidates = named_sweep(prefix, fieldName, values)
candidates = cell(numel(values), 1);
for index = 1:numel(values)
    params = struct();
    params.(fieldName) = values(index);
    candidates{index} = candidate(sprintf('%s_%g', prefix, values(index)), params);
end
end

function value = candidate(name, params)
value = struct('name', name, 'params', params);
end

function combined = merge_params(base, overrides)
combined = base;
fields = fieldnames(overrides);
for index = 1:numel(fields)
    combined.(fields{index}) = overrides.(fields{index});
end
end

function [feasible, stable] = is_feasible(result)
stable = stability_status(result);
feasible = stable ...
    && all(isfinite([result.supp_db, result.extra.u_demand_max])) ...
    && result.extra.u_demand_max <= 4 ...
    && result.extra.saturation_count == 0;
if strcmp(result.demo, 'demo5')
    feasible = feasible && result.extra.case_a_applicable;
end
end

function score = candidate_score(result, feasible, stable)
if ~all(isfinite([result.supp_db, result.extra.u_demand_max]))
    score = -inf;
    return;
end

score = result.supp_db ...
    - 8 * max(0, result.extra.u_demand_max - 4) ...
    - 0.02 * result.extra.saturation_count ...
    - 100 * double(~stable);
if feasible
    score = score + 1000;
end
end

%% ========================================================================
% Demo2 T2 对照：filtered-x Q-RLS vs normalized LMS
%% ========================================================================

function comparison = compare_demo2_t2_adaptation(calibrationSignals, evaluationSignals, ~, ~)
base = struct( ...
    'Q_lqr', 1, ...
    'R_lqr', 1e-2, ...
    'Qn_plant', 1e-4, ...
    'Qn_dist', 0.1, ...
    'Rn', 0.1, ...
    'control_scale', 1, ...
    'ramp_seconds', 0.1, ...
    'bp_band', [280 440], ...
    'adaptive_warmup_seconds', 0.5, ...
    'theta_norm_limit', 8, ...
    'nQ', 32, ...
    'adaptation_method', 'lms', ...
    'lms_epsilon', 1e-6, ...
    'lms_leakage', 0);

stepSizes = [0.001, 0.003, 0.01, 0.03, 0.1];
rows = cell(numel(stepSizes), 10);
scores = -inf(numel(stepSizes), 1);
feasible = false(numel(stepSizes), 1);
calibrationResults = cell(numel(stepSizes), 1);

for index = 1:numel(stepSizes)
    params = base;
    params.adaptation_gain = stepSizes(index);
    candidateName = sprintf('lms_n32_mu%g', stepSizes(index));
    try
        result = controller_demo2(calibrationSignals, 'T2', 'adaptive', params);
        calibrationResults{index} = result;
        stable = stability_status(result);
        feasible(index) = stable ...
            && result.extra.u_demand_max <= 4 ...
            && result.extra.saturation_count == 0;
        local = finite_local_suppression(result);
        worstLocal = min(local);
        meanLocal = mean(local);
        scores(index) = 0.5 * worstLocal + 0.5 * meanLocal ...
            - 8 * max(0, result.extra.u_demand_max - 4) ...
            - 0.02 * result.extra.saturation_count ...
            - 100 * double(~stable);
        rows(index, :) = {candidateName, false, feasible(index), stable, ...
            result.supp_db, worstLocal, meanLocal, ...
            result.extra.u_demand_max, result.extra.saturation_count, ...
            jsonencode(params)};
    catch exception
        rows(index, :) = {candidateName, false, false, false, ...
            NaN, NaN, NaN, NaN, NaN, jsonencode(params)};
        fprintf('Demo2 LMS %s ERROR: %s\n', candidateName, exception.message);
    end
end

feasibleIndices = find(feasible);
if isempty(feasibleIndices)
    [~, selectedIndex] = max(scores);
else
    [~, localIndex] = max(scores(feasibleIndices));
    selectedIndex = feasibleIndices(localIndex);
end

rows{selectedIndex, 2} = true;
tuning = cell2table(rows, 'VariableNames', { ...
    'candidate', 'selected', 'feasible', 'stable', ...
    'suppression_db', 'worst_local_suppression_db', ...
    'mean_local_suppression_db', 'control_demand_max', ...
    'saturation_count', 'params_json'});

selectedParams = base;
selectedParams.adaptation_gain = stepSizes(selectedIndex);
lmsEvaluation = controller_demo2(evaluationSignals, 'T2', 'adaptive', selectedParams);

rlsParams = rmfield(base, {'adaptation_method', 'lms_epsilon', 'lms_leakage'});
rlsParams.nQ = 32;
rlsParams.lambda = 0.98;
rlsParams.F_init = 0.1;
rlsParams.adaptation_gain = 0.15;
rlsParams.adaptation_method = 'rls';
rlsCalibration = controller_demo2(calibrationSignals, 'T2', 'adaptive', rlsParams);
rlsEvaluation = controller_demo2(evaluationSignals, 'T2', 'adaptive', rlsParams);

comparison = struct();
comparison.rls = struct( ...
    'candidate', 'q32_l98_g15', ...
    'params', rlsParams, ...
    'calibration', rlsCalibration, ...
    'evaluation', rlsEvaluation);
comparison.lms = struct( ...
    'candidate', tuning.candidate{selectedIndex}, ...
    'params', selectedParams, ...
    'calibration', calibrationResults{selectedIndex}, ...
    'evaluation', lmsEvaluation, ...
    'feasible', feasible(selectedIndex));
comparison.tuning = tuning;
comparison.selection_basis = 'calibration worst/mean local T2 suppression with control constraints';
end

function local = finite_local_suppression(result)
local = result.supp_breakdown.supp_db;
local = local(isfinite(local));
if isempty(local)
    local = -inf;
end
end
