function definitions = anc_controller_parameter_definitions(controller_id)
%ANC_CONTROLLER_PARAMETER_DEFINITIONS Editable parameters and constraints.
%
% This is the single allow-list used by both the GUI and candidate builder.
% Parameters that select a controller implementation (for example the LMS
% versus RLS branch) are intentionally not editable here.

common = [ ...
    spec('actuator_limit', 'scalar', 0, Inf, [], '', 'Normalized actuator hard limit', 5), ...
    spec('ramp_seconds', 'scalar', 0, Inf, [], 's', 'Control fade-in duration', 0.1), ...
    spec('control_scale', 'scalar', 0, Inf, [], '', 'Control output scale', 1)];

switch char(controller_id)
    case 'demo1_rst_fixed'
        definitions = [ ...
            spec('f_design', 'scalar', 0, Inf, [], 'Hz', 'RST design/tone frequency', 357), ...
            common(1)];

    case 'demo1_qrls'
        definitions = [ ...
            spec('f_design', 'scalar', 0, Inf, [], 'Hz', 'Central RST design frequency', 357), ...
            spec('nQ', 'integer', 1, 512, [], 'tap', 'Youla-Q order', 4), ...
            spec('lambda1', 'scalar', eps, 1, [], '', 'RLS forgetting factor', 0.98), ...
            spec('lambda2', 'scalar', eps, Inf, [], '', 'RLS data weighting', 1), ...
            spec('F_diag', 'scalar', eps, Inf, [], '', 'Initial covariance diagonal', 1e-3), ...
            common(1)];

    case 'demo2_lqg_fixed'
        definitions = [lqg_base(), common];

    case 'demo2_lms'
        definitions = [lqg_base(), adaptive_common(), ...
            spec('lms_epsilon', 'scalar', eps, Inf, [], '', 'NLMS denominator regularization', 1e-6), ...
            spec('lms_leakage', 'scalar', 0, 1, [], '', 'LMS coefficient leakage', 0), ...
            common];

    case 'demo2_qrls'
        definitions = [lqg_base(), adaptive_common(), ...
            spec('lambda', 'scalar', eps, 1, [], '', 'RLS forgetting factor', 0.98), ...
            spec('F_init', 'scalar', eps, Inf, [], '', 'Initial RLS covariance scale', 0.1), ...
            spec('rls_regularization', 'scalar', 0, Inf, [], '', 'Covariance regularization', 1e-9), ...
            common];

    case 'demo3_fir_fixed'
        definitions = [ ...
            spec('N_fir', 'integer', 2, 4096, [], 'tap', 'Fixed FIR length', 16), ...
            spec('f_design', 'scalar', 0, Inf, [], 'Hz', 'FIR interpolation frequency', 357), ...
            common];

    case 'demo3_imc_fxnlms'
        definitions = [ ...
            spec('N_fir', 'integer', 2, 4096, [], 'tap', 'Fixed initializer FIR length', 8), ...
            spec('N_nlms', 'integer', 2, 4096, [], 'tap', 'Adaptive FIR length', 32), ...
            spec('mu_nlms', 'scalar', 0, Inf, [], '', 'Normalized LMS step size', 0.01), ...
            spec('f_design', 'scalar', 0, Inf, [], 'Hz', 'Initializer design frequency', 357), ...
            spec('theta_norm_limit', 'scalar', eps, Inf, [], '', 'Coefficient-vector norm limit', 10), ...
            common];

    case {'demo4_emopso_rst','demo4_emopso_qrls'}
        definitions = [ ...
            spec('nX', 'integer', 1, 64, [], '', 'X polynomial order', 6), ...
            spec('nY', 'integer', 1, 64, [], '', 'Y polynomial order', 3), ...
            spec('f_notch', 'optional_scalar', 0, Inf, [], 'Hz', 'Internal-model notch frequency; [] disables', []), ...
            spec('zeta_notch', 'scalar', 0, 1, [], '', 'Notch damping ratio', 0.01), ...
            spec('H_R', 'nonempty_vector', -Inf, Inf, [], '', 'Fixed R polynomial factor', 1), ...
            spec('H_S', 'nonempty_vector', -Inf, Inf, [], '', 'Fixed S polynomial factor', 1), ...
            spec('P_D_zeta', 'scalar', eps, Inf, [], '', 'Dominant-pole damping ratio', 0.8), ...
            spec('P_D_omega', 'scalar', eps, pi, [], 'rad/sample', 'Dominant-pole natural frequency', 0.25*pi), ...
            spec('seed', 'integer', 0, Inf, [], '', 'eMOPSO random seed', 42), ...
            spec('n_pop', 'integer', 2, Inf, [], '', 'eMOPSO population size', 40), ...
            spec('k_max', 'integer', 1, Inf, [], '', 'eMOPSO iteration budget', 80), ...
            spec('epsilon', 'scalar', 0, Inf, [], '', 'Epsilon-dominance resolution', 0.01), ...
            spec('archive_max', 'integer', 1, Inf, [], '', 'Pareto archive capacity', 50), ...
            spec('score_band', 'vector2', 0, Inf, [], 'Hz', 'Knee-selection frequency band', [100 500])];
        if strcmp(controller_id, 'demo4_emopso_qrls')
            definitions = [definitions, ...
                spec('nQ', 'integer', 1, 512, [], 'tap', 'Youla-Q order', 4), ...
                spec('lambda1', 'scalar', eps, 1, [], '', 'RLS forgetting factor', 0.98), ...
                spec('lambda2', 'scalar', eps, Inf, [], '', 'RLS data weighting', 1), ...
                spec('F_diag', 'scalar', eps, Inf, [], '', 'Initial covariance diagonal', 1e-3)];
        end
        definitions = [definitions, common([3 1])];

    case {'demo5_marino_fixed','demo5_marino_adaptive'}
        definitions = [ ...
            spec('k', 'scalar', 0, Inf, [], '', 'Internal-model injection gain', 1e-3), ...
            spec('freq_init_hz', 'nonempty_vector', eps, Inf, [], 'Hz', 'Initial disturbance frequencies', 357), ...
            spec('freq_min_hz', 'scalar', 0, Inf, [], 'Hz', 'Lower frequency projection bound', 20), ...
            spec('freq_max_hz', 'scalar', eps, Inf, [], 'Hz', 'Upper frequency projection bound', 500), ...
            spec('method', 'choice', NaN, NaN, {'exact','euler'}, '', 'Oscillator discretization', 'exact'), ...
            spec('case_a_min_ratio', 'scalar', 0, 1, [], '', 'Minimum Case-A real-part ratio', 0.1), ...
            spec('feedback_sign', 'choice', NaN, NaN, {'paper','benchmark'}, '', 'Feedback-sign convention', 'paper'), ...
            spec('dc_cancel', 'logical', NaN, NaN, [], '', 'Enable DC internal-model branch', false), ...
            spec('output_timing', 'choice', NaN, NaN, {'updated','previous'}, '', 'Use updated or previous oscillator state', 'updated')];
        if strcmp(controller_id, 'demo5_marino_adaptive')
            definitions = [definitions, ...
                spec('epsilon', 'scalar', 0, Inf, [], '', 'Frequency adaptation gain', 1e-4)];
        end
        definitions = [definitions, common([2 1])];

    case 'imc_fxlms'
        definitions = [ ...
            spec('N_fir', 'integer', 2, 4096, [], 'tap', 'Adaptive FIR length', 64), ...
            spec('mu', 'scalar', 0, Inf, [], '', 'FxLMS normalized step size', 0.01), ...
            spec('delta', 'scalar', eps, Inf, [], '', 'Normalization regularization', 1e-4), ...
            spec('norm_limit', 'scalar', eps, Inf, [], '', 'Coefficient-vector norm limit', 10), ...
            common([2 1])];

    otherwise
        error('anc_controller_parameter_definitions:unknownController', ...
            'Unknown controller id: %s', controller_id);
end
end

function values = lqg_base()
values = [ ...
    spec('augmented', 'logical', NaN, NaN, [], '', 'Use augmented disturbance-state model', true), ...
    spec('Q_lqr', 'scalar', eps, Inf, [], '', 'LQR state penalty', 1), ...
    spec('R_lqr', 'scalar', eps, Inf, [], '', 'LQR control penalty', 0.01), ...
    spec('Qn_plant', 'scalar', eps, Inf, [], '', 'Plant process-noise covariance', 1e-4), ...
    spec('Qn_dist', 'scalar', eps, Inf, [], '', 'Disturbance process-noise covariance', 0.1), ...
    spec('Rn', 'scalar', eps, Inf, [], '', 'Measurement-noise covariance', 0.1)];
end

function values = adaptive_common()
values = [ ...
    spec('nQ', 'integer', 1, 4096, [], 'tap', 'Adaptive Q-filter length', 32), ...
    spec('bp_band', 'vector2', 0, Inf, [], 'Hz', 'Adaptation band [low high]', [300 420]), ...
    spec('adaptive_warmup_seconds', 'scalar', 0, Inf, [], 's', 'Fixed-controller warm-up', 0.5), ...
    spec('adaptation_gain', 'scalar', 0, Inf, [], '', 'Adaptive update scale', 0.1), ...
    spec('theta_norm_limit', 'scalar', eps, Inf, [], '', 'Q coefficient norm limit', 10)];
end

function value = spec(name, type, minimum, maximum, choices, unit, description, default_value)
value = struct('name', name, 'type', type, 'minimum', minimum, ...
    'maximum', maximum, 'choices', {choices}, 'unit', unit, ...
    'description', description, 'default_value', default_value);
end
