function catalog = anc_controller_catalog()
%ANC_CONTROLLER_CATALOG Supported migrated controller design workflows.

catalog = [ ...
    item('demo1_rst_fixed', 'Demo1: low-order RST (fixed)', ...
        'error feedback', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo1_qrls', 'Demo1: RST + Youla-Q RLS', ...
        'error feedback with reconstructed disturbance', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo2_lqg_fixed', 'Demo2: augmented LQG (fixed)', ...
        'error feedback and Kalman disturbance state', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo2_lms', 'Demo2: LQG + normalized LMS', ...
        'error feedback and filtered-x adaptation', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo2_qrls', 'Demo2: LQG + Q-RLS', ...
        'error feedback and filtered-x adaptation', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo3_fir_fixed', 'Demo3: F(z) + fixed FIR', ...
        'source reference and secondary-path model', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo3_imc_fxnlms', 'Demo3: IMC-FxNLMS', ...
        'source reference and secondary-path model', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false), ...
    item('demo4_emopso_rst', 'Demo4: eMOPSO-shaped RST (fixed)', ...
        'error feedback; offline multi-objective optimization', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, true), ...
    item('demo4_emopso_qrls', 'Demo4: eMOPSO RST + Youla-Q RLS', ...
        'error feedback; optimized center plus adaptation', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, true), ...
    item('demo5_marino_fixed', 'Demo5: Marino-Tomei fixed internal model', ...
        'error microphone only; constant periodic disturbance', {'fixed_sine','multisine'}, false), ...
    item('demo5_marino_adaptive', 'Demo5: Marino-Tomei frequency adaptation', ...
        'error microphone only; narrowband frequency model', {'fixed_sine','linear_chirp','multisine'}, false), ...
    item('imc_fxlms', 'Demo5 baseline: feedback IMC-FxLMS', ...
        'error microphone only; internal reference reconstruction', {'fixed_sine','linear_chirp','bandlimited_noise','white_noise','multisine','file'}, false) ...
    ];
end

function value = item(id, label, information, noise_types, expensive)
value = struct('id', id, 'label', label, 'information', information, ...
    'noise_types', {noise_types}, 'expensive', expensive);
end
