function cfg = anc_migration_config()
%ANC_MIGRATION_CONFIG Default configuration for model/controller migration.
%
% The configuration is deliberately serializable.  It can be edited from a
% script, populated by anc_migration_designer_gui, and saved with every run.

tool_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(tool_dir);

cfg = struct();
cfg.format_version = 1;
cfg.project_root = project_root;
cfg.model_root = fullfile(project_root, 'sysid_models', '20260718');
cfg.models = struct( ...
    'primary_file', '', ...
    'secondary_file', '', ...
    'sample_rate_tolerance', 0.01, ...
    'control_delay_samples', 1);

cfg.noise = struct( ...
    'type', 'fixed_sine', ...
    'duration', 6, ...
    'amplitude_rms', 0.8, ...
    'frequency_hz', 357, ...
    'low_hz', 300, ...
    'high_hz', 420, ...
    'frequencies_hz', [320 357 400], ...
    'filter_order', 128, ...
    'seed_calibration', 42, ...
    'seed_evaluation', 142, ...
    'file', '', ...
    'reverse_evaluation_chirp', true);

cfg.design = struct( ...
    'controller_id', 'demo1_qrls', ...
    'profile', 'standard', ...
    'auto_tune', true, ...
    'manual_params', struct(), ...
    'candidate_limit', Inf, ...
    'actuator_limit', 5, ...
    'tuning_demand_limit', 4, ...
    'success_suppression_db', 20, ...
    'progress_callback', []);

cfg.output = struct( ...
    'save', true, ...
    'file', '', ...
    'overwrite', false, ...
    'plot', true);
end
