function generate_broadband_report(stage, ~, testDir, partFilter)
%GENERATE_BROADBAND_REPORT Write the independent T3 failure-boundary report.

if nargin < 4, partFilter = 'report'; end
if ~isempty(partFilter) && ~strcmp(partFilter, 'report')
    return;
end
if ~isfield(stage, 'scope') || ~strcmp(stage.scope, 'broadband')
    error('generate_broadband_report:WrongScope', ...
        'Expected a broadband stage generated by run_cylinder1dm_stage(''broadband'').');
end

reportPath = fullfile(testDir, 'BROADBAND_CYLINDER1DM_REPORT.md');
fid = fopen(reportPath, 'w', 'n', 'UTF-8');
if fid < 0, error('Cannot write report: %s', reportPath); end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '# Cylinder 1 dm 宽带控制独立边界报告\n\n');
fprintf(fid, '## 1. 本报告要回答什么\n\n');
fprintf(fid, ['本报告只评估 100–500 Hz 随机宽带噪声，不参与 T1 定频与 T2 扫频的 ' ...
    'fixed/adaptive 主比较。目的不是为四种方法排名，而是独立确认现有宽带设计是否在统一约束下有效。\n\n']);
fprintf(fid, ['成功要求为：内部稳定、评价抑制不低于 20 dB、未限幅控制需求不超过 4，' ...
    '且不发生硬限幅。任一条件不满足即判定无效。\n\n']);

fprintf(fid, '## 2. 独立实验设置\n\n');
fprintf(fid, '| 项目 | 设置 |\n');
fprintf(fid, '|---|---|\n');
fprintf(fid, '| 场景 | T3，100–500 Hz 带限白噪声 |\n');
fprintf(fid, '| 校准/评价 | 校准 seed 42；评价 seed 142，参数冻结后评价 |\n');
fprintf(fid, '| 执行器 | 调参未限幅峰值上限 4；硬限幅 5 |\n');
fprintf(fid, '| 比较内容 | 开环/闭环 PSD、移动抑制、未限幅需求、限幅次数 |\n');
fprintf(fid, '| 主实验关系 | 与 `run_cylinder1dm_stage()` 完全分开，不改变 T1/T2 结果 |\n\n');

fprintf(fid, '## 3. 冻结评价摘要\n\n');
fprintf(fid, '| Demo | Design | Candidate | Calibration dB | Evaluation dB | Demand | Clips | Stable | Effective |\n');
fprintf(fid, '|---|---|---|---:|---:|---:|---:|---|---|\n');
for index = 1:height(stage.summary)
    profile = broadband_profile(stage.summary.demo{index});
    fprintf(fid, '| %s | %s | %s | %.2f | %.2f | %.3f | %d | %s | %s |\n', ...
        upper(stage.summary.demo{index}), profile.method, ...
        stage.summary.candidate{index}, ...
        stage.summary.calibration_suppression_db(index), ...
        stage.summary.evaluation_suppression_db(index), ...
        stage.summary.control_demand_max(index), ...
        stage.summary.saturation_count(index), ...
        yes_no(stage.summary.stable(index)), ...
        yes_no(stage.summary.evaluation_success(index)));
end

fprintf(fid, '\n## 4. 各宽带设计的证据与结论\n\n');
for index = 1:numel(stage.selections)
    selection = stage.selections(index);
    result = stage.evaluation_results{index};
    profile = broadband_profile(selection.demo);
    summaryIndex = find(strcmp(stage.summary.demo, selection.demo), 1);
    tuningRows = strcmp(stage.tuning.demo, selection.demo);
    feasibleCount = sum(stage.tuning.feasible(tuningRows));

    fprintf(fid, '### %s：%s\n\n', upper(selection.demo), profile.method);
    fprintf(fid, '**作用与目的**：%s\n\n', profile.purpose);
    fprintf(fid, ['**具体设置**：100–500 Hz 带限白噪声；校准与评价使用不同随机种子；' ...
        '候选仅在校准集选择，随后冻结到评价集。\n\n']);
    fprintf(fid, '**比较内容**：开环与闭环宽带 PSD、时变抑制、未限幅控制需求和硬限幅次数。\n\n');
    fprintf(fid, '![%s T3 analysis](figures/cylinder1dm_2k/%s/t3_analysis.png)\n\n', ...
        upper(selection.demo), selection.demo);
    write_broadband_figure_interpretation(fid, result);
    fprintf(fid, ['**冻结结果**：候选 `%s`；校准 %.2f dB，评价 %.2f dB；' ...
        '未限幅需求 %.3f；限幅 %d 次；%d 个候选满足调参可行性；判定为 **%s**。\n\n'], ...
        selection.candidate, selection.calibration_result.supp_db, ...
        result.supp_db, result.extra.u_demand_max, ...
        result.extra.saturation_count, feasibleCount, ...
        effectiveness_word(stage.summary.evaluation_success(summaryIndex)));
    if ~selection.feasible
        fprintf(fid, '当前冻结项是惩罚评分最高的失败候选，不代表已得到可行宽带控制器。\n\n');
    end
    fprintf(fid, '**结果解释**：%s\n\n', profile.interpretation);
    fprintf(fid, '**本场景结论**：%s\n\n', profile.conclusion);
end

fprintf(fid, '## 5. 总结\n\n');
if any(stage.summary.evaluation_success)
    fprintf(fid, '至少一种宽带设计满足统一成功标准；应以表中动态结果为准。\n');
else
    fprintf(fid, ['四种现有宽带设计均未同时满足抑制与控制约束，因此当前结论是“宽带设计无效”。' ...
        '该负面结论只界定 T3，不削弱 T1/T2 对窄带设计和频率跟踪能力的观察。\n']);
end
end

function write_broadband_figure_interpretation(fid, result)
yOpen = result.extra.y_open(:);
yClosed = result.extra.y_closed(:);
uDemand = result.extra.u_demand(:);
windowLength = max(16, round(0.1 * result.fs));
movingOpen = sqrt(movmean(yOpen.^2, windowLength));
movingClosed = sqrt(movmean(yClosed.^2, windowLength));
movingSuppression = 20 * log10(movingOpen ./ max(movingClosed, 1e-12));
finiteSuppression = movingSuppression(isfinite(movingSuppression));
if isempty(finiteSuppression)
    minSuppression = NaN;
    medianSuppression = NaN;
else
    minSuppression = min(finiteSuppression);
    medianSuppression = median(finiteSuppression);
end
lineDifference = NaN;
if isfield(result.extra, 'u')
    lineDifference = max(abs(uDemand - result.extra.u(:)));
end

fprintf(fid, ['**图像解读**：左上移动 RMS 面板用于判断宽带抑制是否随时间保持，' ...
    '右上 PSD 面板用于检查 100–500 Hz 是否整体下降；本例移动抑制的中位数 %.2f dB、' ...
    '最小值 %.2f dB，说明总体数值不能掩盖时变失效。左下橙色需求峰值的最大值为 %.3f，' ...
    '并在硬限幅 %d 次的情况下与阈值 4/5 比较。'], ...
    medianSuppression, minSuppression, result.extra.u_demand_max, result.extra.saturation_count);
if isfinite(lineDifference) && lineDifference < 1e-9 && result.extra.saturation_count == 0
    fprintf(fid, '橙色需求与实际控制量完全重合且没有硬限幅，说明该失败不是由饱和造成。');
elseif isfinite(lineDifference)
    fprintf(fid, '橙色需求与实际控制量最大差为 %.3g；差异出现的区段就是限幅压缩造成的性能风险。', lineDifference);
else
    fprintf(fid, '该 T3 结果未保存实际施加量，因此需求曲线只能作为限幅风险证据，不能替代实际输出曲线。');
end
fprintf(fid, '右下时变抑制曲线若低于 20 dB，表示对应时间窗口未达到工程成功标准。\n\n');
end

function profile = broadband_profile(demo)
switch demo
    case 'demo1'
        profile = struct( ...
            'method', '低阶 Youla-Q RLS', ...
            'purpose', '检验低阶 Q 能否把窄带 RST 中央控制器扩展为宽带控制器。', ...
            'interpretation', '抑制接近零且控制需求远超约束并触发限幅，说明当前低阶 Q 与饱和处理不足。', ...
            'conclusion', '现有 RST/Youla 宽带设计无效。');
    case 'demo2'
        profile = struct( ...
            'method', '固定宽带 LQG', ...
            'purpose', '检验低阶随机扰动模型和固定 LQG 权重能否预测并抑制宽带实现。', ...
            'interpretation', '控制量保持很小但抑制接近零，瓶颈是随机扰动建模与权重结构，而非饱和。', ...
            'conclusion', '现有宽带 LQG 设计无效。');
    case 'demo3'
        profile = struct( ...
            'method', 'Jafari NLMS-on-FIR', ...
            'purpose', '检验增加 FIR 自由度后能否在执行器约束内实现宽带自适应。', ...
            'interpretation', '评价抑制没有改善，同时未限幅需求与限幅次数均违反约束。', ...
            'conclusion', '现有 NLMS-on-FIR 宽带设计无效。');
    otherwise
        profile = struct( ...
            'method', 'eMOPSO 整形 RST + 低阶 Q-RLS', ...
            'purpose', '检验多目标整形中央控制器叠加低阶 Q 后的宽带能力边界。', ...
            'interpretation', '虽有部分抑制，但依赖大幅超限控制并频繁饱和，不能视为工程有效。', ...
            'conclusion', '现有 eMOPSO/Youla 宽带设计无效。');
end
end

function value = effectiveness_word(flag)
if flag, value = '有效'; else, value = '无效'; end
end

function value = yes_no(flag)
if flag, value = 'yes'; else, value = 'no'; end
end
